package fiap.cap06aExceptions;

public class TestExceptions5 {

	public static void main(String[] args) throws Exception {
		
		Calculadora2 calc = new Calculadora2();
		
		
		System.out.println(calc.dividir(2, 0));
		

	}

}
